#+TITLE: Дизайн-документ
#+AUTHOR: Vladimir Ryazansew
#+EMAIL: elf.forest@yandex.ru
#+DATE: Вторник, марта 19 2024
#+DESCRIPTION: Org-HTML export made simple.
#+KEYWORDS:  org-mode, export, html, theme, style, css, js, bigblow
#+LANGUAGE:  ru
#+OPTIONS:   H:4 toc:t num:2
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css"/>

*Дизайн-документ для: игры*
 *зелёный мир эльфов*(greenWorldOfElves)

#+begin_quote
Тут должна быть короткая шутка про игру
#+end_quote

“Или здесь”™

All work Copyright ©2024 Владимир Рязанцев (2024)

Автор – Владимир Рязанцев


Версия # 1.00



* История дизайна

	В данной статье даётся краткое описание истории этого документа.

	В этом пункте описывают читателю то, чего вы пытаетесь достичь с историей дизайна.  Не исключено, что они не знают, что это такое, и вы должны объяснить им это.

** Версия 1.10

	Версия 1.10 включает в себя некоторые дополнительные регулировки и настройки, которые я сделал после начального этапа дизайна.  Вот то, что я изменил.

Я переписал раздел о том, как игра работает и его систему.
Я включил отзывы от команды во всех частях дизайна.
И остальные несерьёзные изменения в документе.

* Обзор игры

** Философия

*** Философский пункт #1

	Эта игра пытается сделать всевозможные вещи.  По сути, я пытаюсь добиться того, что никогда не достигалось прежде.  Или. Эта игра будет вовсе пытаться изменить мир.  Мы обдираем конкурентов так точно, что я не могу в это поверить.  Мир будет потрясён тем, как мы используем существующий движок с новым искусством.

*** Философский пункт #2

	Наша игра работает только на компьютерах Compaq.  Причина этого - такие и такие.  По нашему мнению мир идёт к концу, но, так или иначе, какая это разница?

*** Философский пункт #3

	При создании некоторых из этих всеобъемлющих философских пунктов о вашем дизайне, говорите всё, что вы хотите.  Кроме того, не стесняйтесь изменять его на "Моя цель в гейм-дизайне" или на что-либо другое.

* Часто задаваемые вопросы

** Что такое игра?

Опишите игру.  Это и есть самый распространённый вопрос, который вам зададут.  Над чем вы работаете?

** Зачем создавать эту игру?

	Почему вы создаёте эту игру?  Вам нравятся 3D-шутеры?  Вы думаете, что всё-таки для вас есть место на рынке?

** Какое место занимает игра?

	Опишите мир, в котором происходят действия вашей игры.  Проще простого.  Помогите читателю сформулировать его в сознании, написав здесь несколько предложений.  Вы можете в конце описать более подробно в разделе, посвящённом специально для описания мира.  Не забывайте, что мы хотим сохранить эту часть дизайна наиболее удобно читаемой.

** Что я могу контролировать?

	Опишите то, что и чем игрок будет управлять.  Вы будете отвечать за группу бешеных мутантов скрипачей.  Если хотите, вы можете включить ИИ и превратить его в симуляцию аквариума.

** Сколько я могу контролировать?

	Если это того касается, говорите немного больше о выборе элементов управления.  Не забудьте добавить ответы на вопросы, которые, как вы считаете, может спросить читатель.  Это полностью зависит от вашего дизайна.
** Что находится в центре внимания?

	Теперь мы знаем, где происходят действия игры, и чем игрок управляет.  Чего они должны достичь на этом свете?  Злые скрипачи должны захватить здание ООН.  Будьте осторожны, чтобы не добавить кучу барахла.  Ваш дизайн должен оставаться читаемым и информативным.

** Что изменилось?

Скажите им, чем отличается ваша игра от других игр, которые прямо сейчас пытаются продаваться на рынке.  Возникает целый ряд вопросов.

* Набор свойств

** Общие свойства

Огромный мир
Игроки
3D-графика
32-битный цвет

** Многопользовательские свойства

До 10 миллионов игроков
Лёгкий путь найти игру
Лёгкий путь найти своего приятеля в огромном мире
Возможность общаться по голосовой связи

** Редактор

Поставляется с редактором мира
Скачивание уровней из интернета
Редактор супер удобный в использовании

** Геймплей

Список вещей, которые являются ключевыми в игровом опыте
Огромный список многих вещей
Эй, если у тебя здесь ничего, то стоит ли вообще делать игру?

* Игровой мир

** Обзор

	Представьте общий обзор игрового мира.

** Свойства мира #1

	Этот раздел не должен называться Свойства мира #1, но он должен хоть как-то называться.  Здесь вы должны огромный кусок геймплея сломать на составные части и описать каждый из них.

** Свойства мира #2

	То же самое и здесь.  Но ещё здесь нужно описать, как вы будете продавать игру.

** Физика мира

*** Обзор

	Опишите свой мир.  Затем опишите составляющие этого мира ниже в каждом пункте.

Ниже описаны основные компоненты вашего материального мира.

*** Основные места

	Опишите здесь основные места в мире (например, где происходят действия игры; какие локации встречаются чаще; какие места имеют обучающий элемент или сильно взаимосвязаны с сюжетом игры)

*** Движение

	Опишите, как игрок взаимодействует с другими персонажами и что игроку нужно для достижения цели/ей.

*** Масштаб

	Опишите, каков размер вашего мира.  Это важно.

*** Объекты

	Опишите все объекты, которые можно найти в мире.

*** Погода

	Опишите погодные изменения в вашем мире. В противном случае пропустите этот раздел. 

*** День и Ночь

	В вашей игре день сменяется ночью и наоборот?  Если да, то опишите это здесь.
*** Время
	Опишите, насколько скорость времени в вашем мире отличается от реального мира.
* Рендеринг системы

** Обзор

	Опишите то, как ваша игра будет отображаться, а затем углубитесь в детали в следующем пункте.

** 2D/3D Рендеринг

	Опишите, какой 2D/3D движок будет использоваться.

* Камера

** Обзор

Опишите, каким образом камера будет работать, а потом углубитесь в детали, если камера в плане реализации является очень сложной.

** Свойство камеры #1

	Как камера перемещается.

** Свойство камеры #2

	Где камера перемещается по-другому.

* Игровой движок


** Обзор

	Опишите игровой движок в целом.

** Свойство игрового движка #1

	Движок игры будет отслеживать в мире то или то.

** Жидкость

	Как движок будет обрабатывать воду.

** Обнаружение столкновений

	Наш игровой движок обрабатывает обнаружение столкновений действительно хорошо. Он использует такую и такую технику и выглядит превосходно.




* Модель освещения

** Обзор

	Опишите модель освещения, которую вы собираетесь использовать, а затем разберите его в различных аспектах ниже.
** Свойство модели освещения #1

	Мы используем xyz технику, чтобы осветить наш мир.

** Свойство модели освещения #2

	Зачем освещать баклажаны в игре, если они при любых обстоятельствах фиолетовые.

* Расположение мира

** Обзор

	Опишите это кратко.

** Свойство мира #1

** Свойство мира #2

* Игровые персонажи

** Обзор

	Опишите ваших персонажей.

** Создание персонажа

	Как вы создаёте или изменяете персонажей.

** Враги и Монстры

	Опишите врагов или монстров в мире или кого-либо ещё, с кем игрок будет сражаться.  Естественно, это сильно зависит от вашей идеи игры, но, как правило, должна быть попытка что-нибудь убить.

* Пользовательский интерфейс

** Обзор

	Опишите составляющие пользовательского интерфейса в разделах ниже.

** Свойство пользовательского интерфейса #1

** Свойство пользовательского интерфейса #2

* Оружие

** Обзор

	Опишите оружие, используемое в игре.

** Свойство оружия #1

** Свойство оружия #2

* Музыка и звуковые спецэффекты


** Обзор

	Ну, думаю, смысл вы поняли.	

** Справочник аудио

	Если вы используете справочник, то опишите ваш план здесь.  Если нет, то что вы используете?	

** 3D Звук

	Какие API-функции вы собираетесь использовать или не использовать в зависимости от обстоятельств.	

** Звуковое оформление

	Что вы собираетесь сделать со звуковым оформлением на этом раннем этапе.  Эй, опиши хорошо, чтобы читатель знал, о чём вы думаете.

* Однопользовательская игра

** Обзор

	Опишите игровой опыт сингла в нескольких предложениях.

	Вот разбивка ключевых компонентов одиночной игры.

** Свойство однопользовательской игры #1

** Свойство однопользовательской игры #2

** История

	Опишите свою идею истории здесь, а затем направьте их в дополнении или отдельные документы, которые обеспечат всю необходимую информацию об истории.

** Время геймплея

	Сколько времени займёт полное прохождение одиночной игры.

** Условия победы

	Что приводит к победе игрока в одиночной игре?

* Многопользовательская игра

** Обзор

	Опишите в нескольких предложениях, как многопользовательская игра будет работать.

** Максимальное количество игроков

	Опишите, сколько игроков могут играть одновременно.


** Серверы

	У вас клиент-сервер или информация передаётся от одного самостоятельного узла к другому, или что-либо другое.

** Настройка

	Опишите, как игроки могут настроить мультиплеер.

** Интернет

	Опишите, как ваша игра будет работать через интернет.

** Игровые сайты

	Опишите, какие игровые сайты вы хотите поддержать, и какие технологии вы собираетесь использовать для достижения этой цели.  Возможно, Dplay или TCP/IP, или что-либо другое.

** Постоянство

	Опишите, ваш мир меняется или нет.

** Сохранение и Загрузка

	Объясните, как вы можете сохранить опыт в многопользователькой игре, а затем загрузить его.  Если вы можете или почему это невозможно.

* Визуализация персонажа

** Обзор

	Больше информации относительно ваших персонажей.

** Свойство визуализации персонажа #1

** Свойство визуализации персонажа #2

* Редактирование мира

** Обзор

	Кратко опишите редактор мира.

** Свойство редактирования мира #1

** Свойство редактирования мира #2

* Дополнительные материалы

** Обзор

Все остальные материалы, которые не вошли в разделы выше.

Я работаю над…

** Сумасшедшая идея #1

** Сумасшедшая идея #2

*  “XYZ Дополнение”
	Также некоторые дополнительные материалы можно описать здесь. Вот несколько примеров…

*  “Объекты Дополнение”
* “Пользовательский интерфейс Дополнение”
* “Организация сети Дополнение”
* “Визуализация персонажа и анимации Дополнение”
*  “История Дополнение”

	Хорошо, вот и всё.  Я хотел провести больше времени за этим и действительно сделать его большой инструкцией для реализации дизайна игры.  К сожалению, это заняло бы уйму времени, и это то, что нам не хватает в этом бизнесе.  Думаю, что вы поняли идею.  Кроме того, создаётся впечатление, что информация в ней предоставлена в особом порядке, но, на самом деле, она в таком порядке случайно зародилась в моей голове.  Этот макет не является идеальным документом, поэтому можете его изменять на своё усмотрение.

	Удачи и тому подобное!

	Владимир Рязанцев
